name: CI
on:
  push

jobs:
  ci:
    environment:
      name: master
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.4.0]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install project dependencies
        run: poetry install
      - name: Generate JSON with sample data
        run: poetry run python src/generate.py  
        env:
            YOUTUBE_RESULTS_JSON: test/test_results.json
      - name: Generate Vue Static HTML
        run: npm install && npm run generate
        working-directory: overwatch-index