name: FetchAndPublish
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */4 * * *"

jobs:
  ci:
    environment:
      name: master
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.4.0]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install project dependencies
        run: poetry install
      - name: Run Fetch command
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          PLAYLIST_ID: PLiHBUcQP9Nl4zO7cekAzFS-FU0fi3A3Gr # 'pleb vod reviews'
        run: poetry run python src/fetch.py
      - name: Generate JSON
        run: poetry run python src/generate.py  
      - name: Generate Vue Static HTML
        run: npm install && npm run generate
        working-directory: overwatch-index
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./overwatch-index/dist
          cname: overwatch.website
